name       : vamp-plugin-sdk
version    : '2.10'
release    : 4
source     :
    - https://github.com/c4dm/vamp-plugin-sdk/archive/vamp-plugin-sdk-v2.10.tar.gz : b552bc91817294c7f90ea07d70938642ebf15d5e3bafc81cf7d55efab9995399
license    : MIT
component  : programming.library
summary    : The Vamp audio analysis plug-in system
description: |
    The Vamp audio analysis plug-in system
builddeps  :
    - pkgconfig(sndfile)
setup      : |
    %patch -p1 < $pkgfiles/01-fix_multiarch.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    # Doesn't accept --disable-static
    rm $installdir/usr/lib64/*.a
check      : |
    %make test
