name       : vamp-plugin-sdk
version    : 2.6
release    : 1
source     :
    - https://code.soundsoftware.ac.uk/attachments/download/1520/vamp-plugin-sdk-2.6.tar.gz : d0d3578137ac0c1e63f31561081a8d61da526a81152bc1dc9383b629bc07f85f
license    : MIT
summary    : The Vamp audio analysis plug-in system
description: |
    The Vamp audio analysis plug-in system
builddeps  :
    - pkgconfig(sndfile)
setup      : |
    sed '317,328d' -i Makefile.in
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
    rm $installdir/usr/lib/*.la
