name       : vamp-plugin-sdk
version    : 2.7.1
release    : 3
source     :
    - https://github.com/c4dm/vamp-plugin-sdk/archive/vamp-plugin-sdk-v2.7.1.tar.gz : 5d0adef7546d028c8d1363263f84bde4385d8f382017e0de25790fd5a4751d15
license    : MIT
component  : programming.library
summary    : The Vamp audio analysis plug-in system
description: |
    The Vamp audio analysis plug-in system
builddeps  :
    - pkgconfig(sndfile)
setup      : |
    %patch -p1 < $pkgfiles/01-fix_multiarch.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    # Doesn't accept --disable-static
    rm $installdir/usr/lib64/*.a
check      : |
    %make test
